services:
  # It's our Postgres database
  db:
    image: postgres
    restart: always
    ports:
      - 127.0.0.1:1234:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=ragaraw

  # It's a Web interface to interact with our Postgres db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  postgres-data: